# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170920_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
