# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('scale', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_amount',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.QuantityType'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Quantity'),
        ),
    ]
